name: Deploy Locally to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

  steps:   
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy HTML files to Web Directory
      run: |
        sudo cp -r ./* /var/www/html
       
    - name: Verify Deployment
      run: |
        echo "Deployment complete. Checking Nginx status .."
        sudo systemctl is-active nginx
