name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch: # Manual trigger

env:
  NODE_VERSION: '24.x'
  APP_NAME: 'vanilla-app'

jobs:
  ci_stage:
    name: 'quality'
    runs-on: self-hosted

    steps:
      - name: Checkout Code     
        uses: actions/checkout@v4

      - name: Validate Syntax
        run: |
          npm install -g htmlhint
          htmlhint *.html

  cd_stage:
    runs-on: self-hosted
    needs: ci_stage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy HTML to Nginx Web Root
        run: |
          echo "CI Passed! Deploying files to /var/www/html/..."
          sudo cp -r ./* /var/www/html/

      - name: Reload Nginx Server
        run: |
          sudo systemctl reload nginx
          echo "Site is live"
